### ISSUE TITLE
Automatic high performance Header/Footer detection

### ISSUE THREAD

**Issue by aarohijohal** [axa-group/Parsr#10]
The current header/footer detection module `HeaderFooterDetectionModule` requires an estimate in percentage of the maximal distance from the page limit, where the header and footers lie.
It would be great to have this module automatically detect headers and footers (using techniques like NLP, Vision, etc) without the need of such a parameter.

**Comment by jcsrb** [comment]
[here](https://assets.publishing.service.gov.uk/media/5dea3f40e5274a06d8fe2e37/Ms_T_Lyon_and_others_v_Asel_Fashion_Limited__in_Creditors__Voluntary_Liquidation__-_2410405_2019_and_others_-_Judgment.pdf) is a public sample file with a big recurring header, it might be useful as sample file

**Comment by aarohijohal** [comment]
> [here](https://assets.publishing.service.gov.uk/media/5dea3f40e5274a06d8fe2e37/Ms_T_Lyon_and_others_v_Asel_Fashion_Limited__in_Creditors__Voluntary_Liquidation__-_2410405_2019_and_others_-_Judgment.pdf) is a public sample file with a big recurring header, it might be useful

Definitely a useful test document! Thanks!

**Comment by aarohijohal** [comment]
> [here](https://assets.publishing.service.gov.uk/media/5dea3f40e5274a06d8fe2e37/Ms_T_Lyon_and_others_v_Asel_Fashion_Limited__in_Creditors__Voluntary_Liquidation__-_2410405_2019_and_others_-_Judgment.pdf) is a public sample file with a big recurring header, it might be useful

I tried a higher percentage for maxMarginPercentage (I tried 25); I was able to eliminate the numeric header from the Markdown output. Thanks for the interesting document again @jcsrb !
