### ISSUE TITLE
VUE Demo code refactor

### ISSUE THREAD

**Issue by marianorodriguez** [axa-group/Parsr#113]
In the Vue demo there are many components with duplicated CSS and unused methods/computed values. Also there are many values passed as props that can be fetched directly from the store.

I'm seeing this issue in the "document viewer" view and all its selectors/inspector/filters components on the sidebar.

Doing this refactor will allow us to have a much simpler and clean code, and it will be easier for us to add new features in the future.

**Comment by jvalls-axa** [comment]
UI should be only used for easy play with Parsr then there is no needed to invest more time
