### ISSUE TITLE
PdfMiner using document with Tables crash pipeline execution

### ISSUE THREAD

**Issue by jvalls-axa** [axa-group/Parsr#115]
**Summary**
New pdfminer implementation (word usage only) is crashing pipeline when executing LinesToParagraph module.

**Steps To Reproduce**
1. Select pdfminer as extractor
2. Upload foo.pdf
3. See error in API terminal

[foo.pdf](https://github.com/axa-group/Parsr/files/3711911/foo.pdf)

**Comment by aarohijohal** [comment]
Resolved by PR #117
