### ISSUE TITLE
PdfMiner forces wrong behaviour in WordsToLine Module

### ISSUE THREAD

**Issue by jvalls-axa** [axa-group/Parsr#116]
**Summary**
PdfMiner introduces Character object in the chain making lines to paragraph module to have wrong behaviour.

**Steps To Reproduce**
1. Select PdfMiner
2. Upload foo.pdf

**Expected behavior**
Table words should be embedded into lines

**Actual behavior**
Table words are not embedded into lines

[foo.pdf](https://github.com/axa-group/Parsr/files/3711926/foo.pdf)

**Comment by aarohijohal** [comment]
Resolved in PR #122
