### ISSUE TITLE
Image rotation detection

### ISSUE THREAD

**Issue by poveden** [axa-group/Parsr#144]
**Is your feature request related to a problem? Please describe.**
[Tesseract scanning quality diminishes on rotated/skewed images](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality#rotation--deskewing). Even mildly rotated images, although OCR'd correctly by Tesseract, can yield incorrect word ordering, specially on counter-clockwise rotations.

**Describe the solution you'd like**
Add rotation correction before feeding the image to Tesseract.

**Describe alternatives you've considered**
The above link actually does a pretty good job at offering options. Even dewarping options are explored there.

Additionally, I've found an article about [Flattening curved documents in images](https://www.researchgate.net/publication/4156408_Flattening_curved_documents_in_images), but I don't know if the solution is already covered above.

**Comment by aarohijohal** [comment]
Solved in #222
