### ISSUE TITLE
Extract everything from a text+images document

### ISSUE THREAD

**Issue by marianorodriguez** [axa-group/Parsr#179]
Like the example PDF below, if a document has text + text within images, Parsr should be able to extract all the information.

Current output: (ignoring images if text was found)
<img width="475" alt="Screenshot 2019-10-29 at 16 41 49" src="https://user-images.githubusercontent.com/11478307/67783813-1870c880-fa6b-11e9-93d1-0b1448878b23.png">

[CHIIndexingComplete-40.pdf](https://github.com/axa-group/Parsr/files/3784428/CHIIndexingComplete-40.pdf)

**Comment by aarohijohal** [comment]
Duplicate of #23

**Comment by jvalls-axa** [comment]
Fixed by #342
