### ISSUE TITLE
pdfminer crashes with "NotImplementedError: only algorithm code 1 and 2 are supported" causes the whole app to crash

### ISSUE THREAD

**Issue by D34D10CK** [axa-group/Parsr#188]
**Summary**
When uploading certain PDFs, pdfminer crashes and causes the whole application to crash with this error: 

```Traceback (most recent call last):
parsr_1     |   File "/opt/app-root/src/dist/src/processing/TableDetectionModule/../../../assets/TableDetectionScript.py", line 165, in <module>
parsr_1     |     main()
parsr_1     |   File "/opt/app-root/src/dist/src/processing/TableDetectionModule/../../../assets/TableDetectionScript.py", line 141, in main
parsr_1     |     tables = camelot.read_pdf(pdfFile,  pages=pages, flavor=flavor, line_scale=lineScale)
parsr_1     |   File "/usr/local/lib/python3.7/dist-packages/camelot/io.py", line 111, in read_pdf
parsr_1     |     p = PDFHandler(filepath, pages=pages, password=password)
parsr_1     |   File "/usr/local/lib/python3.7/dist-packages/camelot/handlers.py", line 50, in __init__
parsr_1     |     self.pages = self._get_pages(self.filepath, pages)
parsr_1     |   File "/usr/local/lib/python3.7/dist-packages/camelot/handlers.py", line 75, in _get_pages
parsr_1     |     infile.decrypt(self.password)
parsr_1     |   File "/usr/local/lib/python3.7/dist-packages/PyPDF2/pdf.py", line 1987, in decrypt
parsr_1     |     return self._decrypt(password)
parsr_1     |   File "/usr/local/lib/python3.7/dist-packages/PyPDF2/pdf.py", line 1996, in _decrypt
parsr_1     |     raise NotImplementedError("only algorithm code 1 and 2 are supported")
parsr_1     | NotImplementedError: only algorithm code 1 and 2 are supported
```

**Steps To Reproduce**
1. Upload this file: [axa.uk.home.advanced.pdf](https://github.com/axa-group/Parsr/files/3798208/axa.uk.home.advanced.pdf)
2. Click "submit"

**Expected behavior**
The app should not crash.

**Actual behavior**
The app crashes.

**Screenshots**
![image](https://user-images.githubusercontent.com/5478612/68030294-6aa72900-fcb9-11e9-8162-1f30f50fd890.png)

**Environment**
This happens on my machine running Ubuntu 18.04 as well as on the docker image.

**Comment by aarohijohal** [comment]
Fixed in #196 .

### Repair story:
1. camelot (table detector) was not working since it only works on decrypted PDFs. See [here](https://buildmedia.readthedocs.org/media/pdf/camelot-py/stable/camelot-py.pdf) on Page 14:

> Camelot only supports PDFs encrypted with ASCII passwords and algorithm code 1 or 2.  An exceptionis thrown if the PDF cannot be read

2. qpdf's was repairing the encrypted PDFs but was not passing this new PDF's location to the modules down the chain.
