### ISSUE TITLE
Font-size is always 0px on the Vue demo with Tesseract

### ISSUE THREAD

**Issue by BinaryBrain** [axa-group/Parsr#211]
**Summary**
When sending a PDF with only images (such as a scan) and using TesseractExtractor, the font-size is always 0px so the text is invisible on the web interface.

**Steps To Reproduce**
1. Send a scanned document to the pipeline from the Vue Web Demo
2. Wait and have a look at the Document Viewer

**Expected behavior**
To be able to read the extracted text.

**Actual behavior**
Nothing shows because font-size is 0.

**Additional context**
I tried on the `develop` branch.

**Comment by aarohijohal** [comment]
#### Proposal
@jvalls-axa We could do either one of the following:
- If a document contains other font sizes (along with the zeros), try to render the zero font size elements with the most common font size.
- Irrespective of the other fonts, try to make sure the text element fits inside the bounding box (wrt height or width, whichever is the best fit) and render with the maximum size possible.

**Comment by jvalls-axa** [comment]
Fixed in #229
