### ISSUE TITLE
Autodetection of scanned document doesn't work anymore

### ISSUE THREAD

**Issue by BinaryBrain** [axa-group/Parsr#212]
**Summary**
The autodetection of scanned document seems to be broken.
Code here: https://github.com/axa-group/Parsr/blob/master/server/bin/index.ts#L120-L121

**Steps To Reproduce**
1. Send a scanned PDF with only images in it (no text).

**Expected behavior**
The [program](https://github.com/axa-group/Parsr/blob/master/server/bin/index.ts#L120-L121) should be able to detect that no text has been properly extracted and re-run everything using an OCR.

**Actual behavior**
No detection is made, so no text is outputed (or maybe only whitespaces).

**Environment**
On `develop` branch.

**Additional context**
I tried with the good-old sample4.pdf.

**Comment by jvalls-axa** [comment]
As we added "image" entity to document representation the actual condition is not satisfied.
We will change this condition to only search Words or exclude images from current condition.
