### ISSUE TITLE
Add Possibility to Select Tesseract Extractor in the Web Interface

### ISSUE THREAD

**Issue by BinaryBrain** [axa-group/Parsr#213]
**Is your feature request related to a problem? Please describe.**
One cannot choose to extract a document (PDF, images...) using Tesseract, ABBYY, Google Vision or anything else than Pdfminer. 

**Describe the solution you'd like**
- Add more options to the dropdown.
- Add a dropdown for images as well.
Pretty much like in the [config file](https://github.com/axa-group/Parsr/blob/develop/docs/configuration-file.md#21-extractor-tools) (Google Vision is missing, by the way).

**Comment by jvalls-axa** [comment]
Current UI allows to select:
- PDF Extractors: PdfMiner & PDF.js
- OCR's: Tesseract, Abbyy, Google Vision, Amazon Textract & MS Cognitive services
