### ISSUE TITLE
detection of divided words at end of line 

### ISSUE THREAD

**Issue by marianorodriguez** [axa-group/Parsr#227]
As it's seen below, when a document has a divided word (in this case, 'premiums'), the output word should be joined.

paragraph example:
![Screenshot 2019-11-21 at 10 59 11](https://user-images.githubusercontent.com/11478307/69327779-5b7b2180-0c4e-11ea-992b-22d798c813c9.png)

markdown result:
The ***owner*** makes payments, known as ***premi- ums***

expected result:
The ***owner*** makes payments, known as ***premiums***

sample pdf:
[354-143_pdf.pdf](https://github.com/axa-group/Parsr/files/3874094/354-143_pdf.pdf)

**Comment by jvalls-axa** [comment]
this feature would open a new door (semantic knowledge) that we don't want to go thought for now
