### ISSUE TITLE
ERROR WHEN SELECTING "PDF MINER" FROM THE DROP DOWN MENU

### ISSUE THREAD

**Issue by AyeshaSarwar** [axa-group/Parsr#228]
**Summary**
I went through the whole process/instructions in the readme.txt flie twice. There are two options in the drop down menu, pdf2json and pdfminer. The option "pdf2json" is working fine, but "pdfminer" is not. The process gets completed, but when moves to the document viewer, nothing is displayed, and on inspection, it says file not found.

**Steps To Reproduce**
In two different terminals, first:

npm run start:api
then in the other one:

cd demo/vue-viewer && npm install && npm run serve
Open localhost:8080 with your favorite browser to use the GUI.

**Expected behavior**
It should display the processed file.

**Actual behavior**
After the uploaded pdf file gets processed, it moves to the "Document Viewer" section.

**Screenshots**
![1](https://user-images.githubusercontent.com/51691311/69330106-2386d500-0c74-11ea-90c9-b08fddb1d293.PNG)
![2](https://user-images.githubusercontent.com/51691311/69330109-241f6b80-0c74-11ea-8b5d-a90d0aaab29a.PNG)
![3](https://user-images.githubusercontent.com/51691311/69330110-241f6b80-0c74-11ea-9022-a21601ece777.PNG)

**Environment**
- Other platform details: npm version = 6.12.0
- Hardware: 9th gen and core i7
- OS: Windows 10 x64

**Additional context**
I am unable to find the processed files for pdfminer, since I can found them for pdfjson on my local pc.

**Comment by jvalls-axa** [comment]
@AyeshaSarwar 

'Pdf2Json' option was removed a long time ago so what branch did you clone?

We release version 0.6 yesterday, could you please pull master and try again?

**Comment by AyeshaSarwar** [comment]
Ok, I am going to try it again..

**Comment by AyeshaSarwar** [comment]
I ran it again. I guess the installation of "GraphicsMagick" was missing before, or may be also I was trying some other version.
It is working fine now.
Thank You.
