### ISSUE TITLE
Docker Images - Update to ImageMagick 7

### ISSUE THREAD

**Issue by jvalls-axa** [axa-group/Parsr#239]
**Summary**
Currently running Parsr using docker image will fail when a PDF containing only images is selected because docker is using ImageMagick 6.X.

**Steps To Reproduce**

1. Run `docker-compose` up
2. Select file from Benchmark -> contact-card-photo.pdf
3. See terminal error --> `There was an error running the orchestrator: Error: Cannot find ImageMagick convert tool. Are you sure it is installed?`

**Expected behavior**
`magick convert ....` should not throw an error

**Actual behavior**
`magick convert ....` fails and throws an error

**Comment by aarohijohal** [comment]
1. PR #240 will resolve the error.
2. It is still interesting to upgrade to the new ImageMagick tool in the Docker.

**Comment by jvalls-axa** [comment]
Fixed inPR #240
