### ISSUE TITLE
Tabular markdown export bug on a certain file

### ISSUE THREAD

**Issue by aarohijohal** [axa-group/Parsr#260]
**Summary**
An error upon the markdown export of a PDF file.

**Steps To Reproduce**

1. Use the `develop` branch
2. Send the attached file to the pipeline

**Expected behavior**
A markdown should be generated

**Actual behavior**
No markdown is generated. The following error is observed:

`There was an error running the orchestrator: TypeError: Cannot read property 'startsWith' of undefined`

** File **
[airasia-q1.pdf](https://github.com/axa-group/Parsr/files/3943055/airasia-q1.pdf)

**Comment by marianorodriguez** [comment]
this is fixed in b6da44d095c3438456bc019621285326b010922b :)
