### ISSUE TITLE
Heading elements do not show "level" property

### ISSUE THREAD

**Issue by giampaolo44** [axa-group/Parsr#305]
**Summary**
Heading elements do not show "level" property as [described in the docs](https://github.com/axa-group/Parsr/blob/master/docs/json-output.md#121-text-type).
Which is odd, since the user interface docker version shows that proper level detection is in place.

**Steps To Reproduce**
Always reproductible.
Downloading the JSON through a `$ curl -X GET http://localhost:3001/api/v1/json/...` returns a properly formed JSON. So far everything seems in line with the docs, but this detail.

**Expected behavior**
The JSON expected based on the docs:
`{"id":74329,"type":"heading","properties":{"order":15},"metadata":[],"box":{"l":56.74,"t":301.06,"w":249.85,"h":14.71},"content":[{"id":72712,"type":"line", --->>> "level": 2, <<<---- "properties":{"order":15},"metadata":[],"box":{"l":56.74,"t":301.06,"w":249.85,"h":14.71},"content":[{"id":9137,"type":"word","properties":{"order":184},"metadata":[],"box":{"l":56.74,"t":301.06,"w":26.84,"h":14.71},"content":"Why","font":2},{"id":9138,"type":"word","properties":{"order":185},"metadata":[],"box":{"l":86.75,"t":301.06,"w":9.03,"h":14.71},"content":"is","font":2},{"id":9139,"type":"word","properties":{"order":186},"metadata":[],"box":{"l":98.94,"t":301.06,"w":19.42,"h":14.71},"content":"the","font":2},{"id":9140,"type":"word","properties":{"order":187},"metadata":[],"box":{"l":121.53,"t":301.06,"w":37.28,"h":14.71},"content":"timing","font":2},{"id":9141,"type":"word","properties":{"order":188},"metadata":[],"box":{"l":161.97,"t":301.06,"w":27.43,"h":14.71},"content":"right","font":2},{"id":9142,"type":"word","properties":{"order":189},"metadata":[],"box":{"l":192.56,"t":301.06,"w":16.94,"h":14.71},"content":"for","font":2},{"id":9143,"type":"word","properties":{"order":190},"metadata":[],"box":{"l":212.67,"t":301.06,"w":21.4,"h":14.71},"content":"this","font":2},{"id":9144,"type":"word","properties":{"order":191},"metadata":[],"box":{"l":237.23,"t":301.06,"w":69.37,"h":14.71},"content":"innovation?","font":2}]}]}`

**Actual behavior**
This is the JSON downloaded:
`{"id":74329,"type":"heading","properties":{"order":15},"metadata":[],"box":{"l":56.74,"t":301.06,"w":249.85,"h":14.71},"content":[{"id":72712,"type":"line","properties":{"order":15},"metadata":[],"box":{"l":56.74,"t":301.06,"w":249.85,"h":14.71},"content":[{"id":9137,"type":"word","properties":{"order":184},"metadata":[],"box":{"l":56.74,"t":301.06,"w":26.84,"h":14.71},"content":"Why","font":2},{"id":9138,"type":"word","properties":{"order":185},"metadata":[],"box":{"l":86.75,"t":301.06,"w":9.03,"h":14.71},"content":"is","font":2},{"id":9139,"type":"word","properties":{"order":186},"metadata":[],"box":{"l":98.94,"t":301.06,"w":19.42,"h":14.71},"content":"the","font":2},{"id":9140,"type":"word","properties":{"order":187},"metadata":[],"box":{"l":121.53,"t":301.06,"w":37.28,"h":14.71},"content":"timing","font":2},{"id":9141,"type":"word","properties":{"order":188},"metadata":[],"box":{"l":161.97,"t":301.06,"w":27.43,"h":14.71},"content":"right","font":2},{"id":9142,"type":"word","properties":{"order":189},"metadata":[],"box":{"l":192.56,"t":301.06,"w":16.94,"h":14.71},"content":"for","font":2},{"id":9143,"type":"word","properties":{"order":190},"metadata":[],"box":{"l":212.67,"t":301.06,"w":21.4,"h":14.71},"content":"this","font":2},{"id":9144,"type":"word","properties":{"order":191},"metadata":[],"box":{"l":237.23,"t":301.06,"w":69.37,"h":14.71},"content":"innovation?","font":2}]}]}`

**Screenshots**
[screenshot of Firefox JSON viewer](https://paste.pics/fc441d34b676ae3d19888e207afefe60)

**Environment**

- Reference commit/version: docker image, downloaded ~3 days ago
- Other platform details: API from docker image as provided
- Hardware: AMD workstation
- OS: Linux Fedora 30

**Comment by jvalls-axa** [comment]
Hi @giampaolo44 

Thanks for detailed feedback 👍 

We will fix this bug in next release...

ciao

**Comment by jvalls-axa** [comment]
Fixed in PR https://github.com/axa-group/Parsr/pull/306

**Comment by giampaolo44** [comment]
Sweet, thanks for letting me know.
