### ISSUE TITLE
Running out of Memory on ImageMagick convert step stop quietly (code 0)

### ISSUE THREAD

**Issue by jcsrb** [axa-group/Parsr#347]
**Summary**
When the ImageMagick memory limit is it, converter stops quietly

**Steps To Reproduce**

using latest `axarev/parsr`and `axarev/parsr-ui-localhost` in docker, 
try to convert [this image based pdf](
https://assets.publishing.service.gov.uk/media/5c77d80940f0b603dca6ef91/Mrs_Catherine_Beattie_v_Condorrat_War_Memorial_and_Four_Others__EATS_0019_17_JW.pdf) all default settings

**Expected behavior**
use different exit code and propagate error

**Actual behavior**
`cache resources exhausted` is triggered, process exited with code 0, UI thinks all is good and done

**Logs**
```log
INFO  (parsr-api/6 on ea33c905b839): Since the input file is a PDF with only images, trying to run an OCR on all pages...
INFO  (parsr-api/6 on ea33c905b839): Using extractor: TesseractExtractor
INFO  (parsr-api/6 on ea33c905b839): executing command: convert -colorspace RGB -density 300x300 -compress lzw -alpha remove -background white /tmp/4790273a22e1895493ffe06bfedad3/39a3cd9eb3961de5ce02ecdbc79c1a.pdf /tmp/4790273a22e1895493ffe06bfedad3/samples/Sample_39a3cd9eb3961de5ce02ecdbc79c1a_%03d.jpeg
INFO  (parsr-api/6 on ea33c905b839): executing command error: convert-im6.q16: cache resources exhausted `/tmp/4790273a22e1895493ffe06bfedad3/39a3cd9eb3961de5ce02ecdbc79c1a.pdf' @ error/cache.c/OpenPixelCache/4083.
INFO  (parsr-api/6 on ea33c905b839): {"found":true,"error":"convert-im6.q16: cache resources exhausted `/tmp/4790273a22e1895493ffe06bfedad3/39a3cd9eb3961de5ce02ecdbc79c1a.pdf' @ error/cache.c/OpenPixelCache/4083.\n"}
INFO  (parsr-api/6 on ea33c905b839): Exiting with code 0
INFO  (parsr-api/6 on ea33c905b839): Process exited
```

**Environment**

- Docker

**Additional context**
default ImageMagick memory limit is

`<policy domain="resource" name="memory" value="256MiB"/>`
set in `/etc/ImageMagick-6/policy.xml`

```
identify  -list resource
Resource limits:
  Width: 16KP
  Height: 16KP
  List length: 18.446744EP
  Area: 128MP
  Memory: 256MiB
  Map: 512MiB
  Disk: 1GiB
  File: 786432
  Thread: 2
  Throttle: 0
  Time: unlimited
```

related issue https://github.com/ImageMagick/ImageMagick/issues/396

**Comment by jvalls-axa** [comment]
Hi @jcsrb 

Yesterday we release version 0.11 with a new feature **Image data extraction using OCR**

Have you tried it ??

<img width="628" alt="Screenshot 2020-03-12 at 13 05 10" src="https://user-images.githubusercontent.com/12429149/76519901-20e9fe80-6462-11ea-90b4-33ef43cd0556.png">

Current behaviour that converts all pages to images for ocr running is a legacy behaviour that I guess we will remove soon....

**Comment by jcsrb** [comment]
I missed that option, trying it now - so far 4 pages (of 23) and still going without error 

updating when done

**Comment by jcsrb** [comment]
using `image-detection` `ocrImages: true` option the document was processed without process failures

quality of the resulted markdown with default settings not amazing, but depends on more settings tweaks 

I consider this closed as the new options are available and current default is deprecated
