### ISSUE TITLE
UI Progress Modal doesn't scroll

### ISSUE THREAD

**Issue by jcsrb** [axa-group/Parsr#348]
**Summary**

**Steps To Reproduce**
convert a document that has many steps

**Expected behavior**
see all steps

**Actual behavior**
can't see all steps

**Screenshots**
![image](https://user-images.githubusercontent.com/119011/76521016-a96d9c80-646c-11ea-9b89-5034c83a4bc4.png)

**Environment**
docker `axarev/parsr-ui-localhost`

**Additional context**
happening during https://github.com/axa-group/Parsr/issues/347

**Comment by jvalls-axa** [comment]
Fix will be included in next release.
