### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by niutech** [axa-group/Parsr#363]
Could you please provide a free online Parsr demo instance so that we could quickly test it without deploying a docker image?

There is a [Jupyter notebook](https://colab.research.google.com/github/axa-group/Parsr/blob/master/demo/jupyter-notebook/parsr-jupyter-notebook.ipynb), but it does not work in Google Colaboratory. Maybe prepending these commands will fix it:
```
!git clone https://github.com/axa-group/Parsr.git
%cd Parsr/demo/jupyter-notebook/
!pip install requests pandas ipython Pygments diff-match-patch sxsdiff
```

**Comment by aarohijohal** [comment]
@niutech Thanks for the question. The jupyter notebook provides a demo of how a python based client would use the Parsr server via API, it does not replace the functionality of the Parsr server/engine itself.

The docker image is for now the quickest way to deploy and get Parsr up and running (which in turn can be interacted with using Jupyter for example).

Let me get back to you on if there are any existing online instances of Parsr somewhere.

**Comment by aarohijohal** [comment]
> Let me get back to you on if there are any existing online instances of Parsr somewhere.

No currently running public instances of Parsr online.
The fastest way to get it running is using the lines:

```
docker pull axarev/parsr
docker run -p 3001:3001 axarev/parsr
```
