### ISSUE TITLE
API Calling Using Curl Command

### ISSUE THREAD

**Issue by sjaintdl** [axa-group/Parsr#374]
Hi @jvalls-axa ,

When i am trying to calling the API through CMD.exe  using Curl command but it is giving error that you can see below - 

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>MulterError: Unexpected field<br> &nbsp; &nbsp;at wrappedFileFilter (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\api\server\node_modules\multer\index.js:40:19)<br> &nbsp; &nbsp;at Busboy.&lt;anonymous&gt; (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\api\server\node_modules\multer\lib\make-middleware.js:114:7)<br> &nbsp; &nbsp;at Busboy.emit (events.js:311:20)<br> &nbsp; &nbsp;at Busboy.emit (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\api\server\node_modules\busboy\lib\main.js:38:33)<br> &nbsp; &nbsp;at PartStream.&lt;anonymous&gt; (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\api\server\node_modules\busboy\lib\types\multipart.js:213:13)<br> &nbsp; &nbsp;at PartStream.emit (events.js:311:20)<br> &nbsp; &nbsp;at HeaderParser.&lt;anonymous&gt; (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\api\server\node_modules\dicer\lib\Dicer.js:51:16)<br> &nbsp; &nbsp;at HeaderParser.emit (events.js:311:20)<br> &nbsp; &nbsp;at HeaderParser._finish (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\api\server\node_modules\dicer\lib\HeaderParser.js:68:8)<br> &nbsp; &nbsp;at SBMH.&lt;anonymous&gt; (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\api\server\node_modules\dicer\lib\HeaderParser.js:40:12)</pre>
</body>
</html>

**Comment by jvalls-axa** [comment]
Hi @sjaintdl 

Could you please paste curl command you're using ??

**Comment by sjaintdl** [comment]
Hi @jvalls-axa ,

I 'm using curl command below - 

curl -X POST http://localhost:3001/api/v1/document -H 'Content-Type:multipart/form-data' -F 'file=@CSE.pdf;type=application/pdf' -F 'config=@"D:\Jain University\Final Year\Parsr\Parsr-0.11.2\Parsr-0.11.2\server\defaultConfig.json";type=application/json'

**Comment by jvalls-axa** [comment]
The issue is that CURL in Windows needs to use double quotes instead of singe quote.

Single quote - Failing
![Curl_KO](https://user-images.githubusercontent.com/12429149/77743148-e8c4ed00-7017-11ea-8c6e-7c5be0dabafa.png)



Double quotes - Working
![Curl_OK](https://user-images.githubusercontent.com/12429149/77743158-ecf10a80-7017-11ea-9f41-337ee31ff298.png)

Try this

`curl -X POST http://localhost:3001/api/v1/document -H "Content-Type:multipart/form-data" -F "file=@CSE.pdf;type=application/pdf" -F "config=@D:\Jain University\Final Year\Parsr\Parsr-0.11.2\Parsr-0.11.2\server\defaultConfig.json;type=application/json"`

We will improve our documentation to solve that issue.

**Comment by sjaintdl** [comment]
Thanks @jvalls-axa ,
To help me on this.

**Comment by sjaintdl** [comment]
hi @jvalls-axa , 
but when i using command below to download CSV file - 
curl -X GET   http://localhost:3001/api/v1/csv/559842b883f4b161fead7ca1b29e7b?download=1

then it is not downloading ZIP file, it asking for - 

Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.

[Data.zip](https://github.com/axa-group/Parsr/files/4399679/Data.zip)

And for other download API is not downloading, that only displaying the data on the terminal.

and when i am giving path but is saving as different file that you can see in attachments -

**Comment by jvalls-axa** [comment]
Hi

Just one Google search to find something like [this](https://stackoverflow.com/a/55392035)
