### ISSUE TITLE
npm run install:pre is not working on mac

### ISSUE THREAD

**Issue by lsm-dev** [axa-group/Parsr#383]
**Summary**
The darwin.bash.sh script does not configure an environment that can run all tests.

**Steps To Reproduce**

1. On a clean mac os environment (10.14.6)
2. npm install
3. npm run install:pre
4. npm run tests
5. See errors

**Expected behavior**
All tests should be passing

**Actual behavior**
Some tests are failing

**Comment by marianorodriguez** [comment]
this was fixed on #384
