### ISSUE TITLE
default-config?specs=true returns 404 not found

### ISSUE THREAD

**Issue by larskluge** [axa-group/Parsr#386]
**Summary**
I am trying to run the Parsr UI via docker, but other than the header w/ navigation the page is blank. 

The reason might be that a request to load the `default-config` returns a 404 not found: `http://localhost:3001/api/v1/default-config?specs=true`

**Steps To Reproduce**

As described in the docs: 

1. `docker run -p 3001:3001 axarev/parsr`
2. `docker run -t -p 8080:80 axarev/parsr-ui-localhost:latest`
3. open `http://localhost:8080/` in browser
=> blank page (header loads)

-or-

1. `docker run -p 3001:3001 axarev/parsr`
2. `curl -i "http://localhost:3001/api/v1/default-config?specs=true"`
=> ...404..not found

**Expected behavior**
I'd expect the UI to load

**Actual behavior**
Other than header, the UI is blank

**Environment**
Tested in latest Chrome & Firefox. Same result. 

**Additional context**
I noticed that specs=false actually returns a config.. in case that helps. 

`http://localhost:3001/api/v1/default-config?specs=false`

**Comment by marianorodriguez** [comment]
Hello @larskluge , thanks for your bug report!
This should be fixed on #388.

Could you please pull latest changes from docker and try again?
`docker pull axarev/parsr`
`docker pull axarev/parsr-ui-localhost`

**Comment by larskluge** [comment]
Awesome! Yes, that solves it. Thanks a ton! :)
