### ISSUE TITLE
Regex Matcher

### ISSUE THREAD

**Issue by sjaintdl** [axa-group/Parsr#395]
Hi team, 

Can any help me on that regex macher part how it work if we apply regex on the document and after processing where we will get that particular applied regex result?

Example - 
Suppose we only want to extract the Phone no and Email id instead of whole data.

**Comment by bailly64u** [comment]
Hello,
You have to pass the regex in the configuration file for example:
```
config.cleaner[16][1].queries = [
{
    label: "phone number",
    regex: "[regex]"
      }
];
```

Then in the parsr response file you can get result in the metadata part

**Comment by sjaintdl** [comment]
Thanks jordi, the above issue has been resolved.
