### ISSUE TITLE
Regex Module case sensitive option

### ISSUE THREAD

**Issue by bailly64u** [axa-group/Parsr#412]
**Summary**
If we set `isCaseSensitive` to true in the regex-module, we end up with a case insensitive regex matching.

**Steps To Reproduce**
Enable the regex module in cofiguration file and try to match some expression in a random document. Then enable / disable the `isCaseSensitive` prop in the configuration file.

**Expected behavior**
Should match case insensitive expression if this option is set to true

**Actual behavior**
Match case sensitive expression if `isCaseSensitive` is set to false, and vice-versa

**Environment**
Contenerized applicaiton
This part of the [RegexMatcherModule.ts](https://github.com/axa-group/Parsr/blob/master/server/src/processing/RegexMatcherModule/RegexMatcherModule.ts) module seems wrong to me:
(line 48)
`if (this.options.isCaseSensitive) {
        regexType += 'i';
      }
`

since 'i' mean case insensitive.

**Comment by jvalls-axa** [comment]
Hi @bailly64u 

Next release will include the fix.

Thanks for detailed feedback!

**Comment by jvalls-axa** [comment]
Fixed in release [0.12.0](https://github.com/axa-group/Parsr/releases/tag/v0.12)
