### ISSUE TITLE
Header Detection broken

### ISSUE THREAD

**Issue by jfilter** [axa-group/Parsr#431]
**Summary**
Header detection is broken right now (at least for the Docker images)

**Steps To Reproduce**

1. Start Docker images for API & GUI
2. Upload file
3. toggle `header-detection` off then toggle it on again
4. Upload file again -> Error

**Expected behavior**
No error

**Actual behavior**
Working Header Detection

**Screenshots**
![Screen Shot 2020-05-08 at 03 36 04](https://user-images.githubusercontent.com/3450307/81360815-1607bf00-90dd-11ea-96a9-eef7dfe937d8.png)

**Environment**

- latest Docker images

**Comment by jvalls-axa** [comment]
Hi @jfilter 

Typo error detected in UI 'sorting modules' function.

Next release will have the fix.

Thanks for feedback.

**Comment by jfilter** [comment]
Thanks for fixing!
