### ISSUE TITLE
Migrate from TSLint to ESLint

### ISSUE THREAD

**Issue by aarohijohal** [axa-group/Parsr#437]
Because of [the recent adieu to TSLint](https://medium.com/palantir/tslint-in-2019-1a144c2317a9), there's an [official encouragement to move to ESLint](https://github.com/palantir/tslint/issues/4534) and [a CLI tool that does it automatically](https://github.com/typescript-eslint/tslint-to-eslint-config).
It would be interesting to move the configs to the ESLint ecosystem for better sustainability.

**Comment by jvalls-axa** [comment]
Fixed by #439
