### ISSUE TITLE
ModuleNotFoundError: "no module named sklearn"

### ISSUE THREAD

**Issue by slbayer** [axa-group/Parsr#463]
**Summary**

Using a Docker image downloaded today (6/30/20) for axarev/parsr and axarev/parsr-ui-localhost, processing a PDF via the UI results in an empty "Document viewer", and the second-to-last status request for the job yields a Python module error.

**Steps To Reproduce**

1. docker run -p 3001:3001 axarev/parsr
2. docker run -t -p 8080:80 axarev/parsr-ui-localhost:latest
3. surf to http://localhost:8080 in your browser
4. with the default modules selected, upload a particular PDF document (sadly, I can't share this document with you)

**Expected behavior**

Document appears in "Document viewer" tab.

**Actual behavior**

"Document viewer" tab is blank. Review of AJAX status requests to the backend reveal the following sequence of JSON responses:

```
executing command: python3 /opt/app-root/src/dist/assets/HeadingLevelPrediction.py 12.879 1 3 0 0 1 0.025015634771732333
```

followed immediately by

```
executing command error: Traceback (most recent call last):  File "/opt/app-root/src/dist/assets/HeadingLevelPrediction.py", line 19, in <module>    main()  File "/opt/app-root/src/dist/assets/HeadingLevelPrediction.py", line 11, in main    model = pickle.load(open(filename, 'rb'))ModuleNotFoundError: No module named 'sklearn'
```

followed by a JSON response describing the various files that *should* be available; however, the next status request returns this error:

```
Error: File not found
    at FileManager.checkFile (/opt/app-root/src/api/server/dist/FileManager.js:88:19)
    at FileManager.getFilePath (/opt/app-root/src/api/server/dist/FileManager.js:52:25)
    at ApiServer.<anonymous> (/opt/app-root/src/api/server/dist/api.js:429:49)
    at step (/opt/app-root/src/api/server/dist/api.js:48:23)
    at Object.next (/opt/app-root/src/api/server/dist/api.js:29:53)
    at /opt/app-root/src/api/server/dist/api.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/app-root/src/api/server/dist/api.js:19:12)
    at ApiServer.handleGetFile (/opt/app-root/src/api/server/dist/api.js:420:16)
    at ApiServer.handleGetJson (/opt/app-root/src/api/server/dist/api.js:338:14)
```

So my guess is that the module import is failing, but the backend isn't catching it appropriately and returns the files that it thought were created, but they weren't.

**Screenshots**

**Environment**

Running Docker version 19.03.8, build afacb8b, installed from a madOS install package downloaded 6/30/20 from Docker Hub, on macOS 10.15.5 (most recent Catalina update), on a Mac mini with 16GB of memory

**Additional context**

**Comment by jvalls-axa** [comment]
Hi @slbayer 

We missed to add **sklearn** as python dependency in docker file

Thanks

**Comment by slbayer** [comment]
While you're at it, TableDetectionScript2.py imports tabula, which also fails with the same error.
