### ISSUE TITLE
unable to install via pypi

### ISSUE THREAD

**Issue by notsoprocoder** [axa-group/Parsr#474]
**Summary**
The python clients appears to be unavailable on PyPi.

**Steps To Reproduce**
Following the documentation [here](https://pypi.org/project/parsr-client/) suggests: 
`pip install parsr`
This results in the installation of an unrelated packages (despite pypi suggesting this will install the parsr client).

I have also tried:
`pip install parsr-client`
Raises: ERROR: No matching distribution found for parsr-client

**Environment**
- Other platform details: Python 3.7.0
- OS: iOS

**Additional context**

**Comment by dafelix42** [comment]
Hello,

We are investing it, we will come back to you about it.

Regards

**Comment by dafelix42** [comment]
Hi @notsoprocoder,

Parsr-client need Python >= 3.8, < 4.0

You need first to update your Python version, then by running `pip install parsr-client` it should install all packages for parsr-client.

Let me know if it solve your problem,

**Comment by notsoprocoder** [comment]
@dafelix42 This has fixed the issue - thanks!
