### ISSUE TITLE
GUI tool is blank

### ISSUE THREAD

**Issue by victor-ab** [axa-group/Parsr#476]
**Summary**
GUI tool is blank

**Steps To Reproduce**

`docker run -p 3001:3001 axarev/parsr`
`docker run -t -p 8080:80 axarev/parsr-ui-localhost:latest`

**Expected behavior**
The upload page should open up.

**Actual behavior**
Blank screen in the GUI.
No specific error.
The only visible error is `error: /etc/nginx/conf.d/default.conf is not a file or does not exist`

**Environment**

Reference commit/version: ba9044d
Other platform details: WSL2 4.19.84-microsoft-standard #1 SMP GNU/Linux
Hardware: Processor: i7 9750H
Installed Physical Memory (RAM):	16.0 GB
OS: Windows 10 x64 Version 10.0.19041.388
**Additional context**

**Comment by dafelix42** [comment]
Hi @victor-ab,

Could you give us a screenshot of your terminal when this situation of GUI tool is blank?

**Comment by victor-ab** [comment]
Note that the API itself seems to be working properly.
```
$ docker run -p 3001:3001 axarev/parsr
Starting par.sr API : node api/server/dist/index.js
[2020-07-30T13:58:53] INFO  (parsr-api/7 on 172f21842314): Api listening on port 3001! 
```

```
$ docker run -t -p 8080:80 axarev/parsr-ui-localhost:latest
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
172.17.0.1 - - [30/Jul/2020:13:59:29 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" "-"
172.17.0.1 - - [30/Jul/2020:13:59:29 +0000] "GET /js/app.js HTTP/1.1" 304 0 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" "-"
172.17.0.1 - - [30/Jul/2020:13:59:29 +0000] "GET /js/chunk-vendors.js HTTP/1.1" 304 0 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" "-"
172.17.0.1 - - [30/Jul/2020:13:59:32 +0000] "GET /img/logo.c014b8cd.png HTTP/1.1" 304 0 "http://localhost:8080/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" "-"
172.17.0.1 - - [30/Jul/2020:13:59:32 +0000] "GET /fonts/materialdesignicons-webfont.d0066537.woff2 HTTP/1.1" 304 0 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" "-"
```

**Comment by dafelix42** [comment]
Hello @victor-ab 

Maybe your problem is similar to #463. Docker image has been updated since this.

Be sure to have the last docker image by running 
`docker pull axarev/parsr` and `docker pull axarev/parsr-ui-localhost`.

If it doesn't solve the problem you can list all the container with `docker ps -a`.
Then pick the name of Parsr container, stop it if running `docker stop <container name>` and remove it `docker rm <container name>`
Finally, remove the old parsr images `docker rmi axarev/parsr` and `docker rmi axarev/parsr-ui-localhost`
At this point you would have a clean state and can pull the last images with `docker pull axarev/parsr` and `docker pull axarev/parsr-ui-localhost`.

**Comment by victor-ab** [comment]
@dafelix42 Followed all the mentioned steps. It worked!
Thanks!!!

**Comment by jalberto** [comment]
This still happens in the latest stable docker image v1.2.2, maybe `latest` has been upgraded but not the numbered version tag?
