### ISSUE TITLE
只能处理pdf，不能对图片进行解析？

### ISSUE THREAD

**Issue by yuzi1949** [axa-group/Parsr#487]
API Guide中给了curl传递pdf文件到API的脚本，但是如果想传递图片，比如jpg格式的图片，报错：Unsupported Media Type。
请问是不是只支持PDF的识别？对图片就没法用了？

**Comment by hexapode** [comment]
Parsr support images. 

- What is the format of the image you are trying?

- The chinese installation documentation is not really up to date, could you try to follow https://github.com/axa-group/Parsr/blob/master/docs/usage.md ?

**Comment by BinaryBrain** [comment]
@yuzi1949 Any updates on this?
Otherwise, I will close the issue.
