### ISSUE TITLE
Convert PDFs to flat images

### ISSUE THREAD

**Issue by jalberto** [axa-group/Parsr#511]
**Is your feature request related to a problem? Please describe.**

When a PDF containing images (with text, tablets, etc) is sent to Parsr each layer is extracted in an image (so each page can result in N images with an alpha channel like lines ina table, in one image, and the text in another image).
Some times is preferable to extract each page in a flat image before sending it to OCR.

**Describe the solution you'd like**
Extract each page as a single image

**Describe alternatives you've considered**
An alternative will be to run each PDF with `pdftoppm` before Parsr

**Additional context**
Maybe ys a way to configure pdfminer to do this but I cannot find how in the documentation.

**Comment by BinaryBrain** [comment]
This is against the philosophy of Parsr that is to extract the data from the PDF directly when possible to avoid OCR mistakes.

**Comment by jalberto** [comment]
@BinaryBrain probably I explained it wrongly. Parsr is already doing PDF to image, but is creating a multilayer image instead of a flat one
