### ISSUE TITLE
Unresolved dependencies

### ISSUE THREAD

**Issue by EliasDjab** [axa-group/Parsr#549]
Hi everyone, 
I'm struggling with an error and come to see if somebody has the same : 

I did the installation on a Mac and on a Ubuntu machine, I get the same error
I did the installation of every dependency, did the npm packages installation, started the api server and when I post a request with a pdf document and the config file under I get this error : 

**Error: Module regex-matcher has unresolved dependencies (lines-to-paragraph).** 

Is there somebody with the same problem or knowing how to resolve it ? Thank you ! 

Edit : I tried with several modules and I always get the same error with all the dependencies of the module I called in my config...  

Config : 
```json
{
    "version": 0.9,
    "extractor": {
      "pdf": "pdfminer",
      "ocr": "tesseract",
      "language": ["eng", "fra"]
    },
    "cleaner": [
      [
        "regex-matcher",
        {
          "queries": [
            {
              "label": "Something 1",
              "regex": "Test"
            },
            {
              "label": "Something 2",
              "regex": "Salut"
            }
          ]
        }
      ]
    ],
    "output": {
      "granularity": "word",
      "includeMarginals": false,
      "includeDrawings": false,
      "formats": {
        "json": true,
        "text": false,
        "csv": false,
        "markdown": false
      }
    }
  }
```

**Comment by BinaryBrain** [comment]
Hello!
It's not related to Node dependencies but rather to your pipeline configuration.
It means you need to have more modules in your "cleaner" section.

```json
"cleaner": [
    "words-to-line", { "maximumSpaceBetweenWords": 100 }],
    "lines-to-paragraph",
    [
        "regex-matcher",
        {
            "queries": [
                {
                    "label": "Something 1",
                    "regex": "Test"
                },
                {
                    "label": "Something 2",
                    "regex": "Salut"
                }
            ]
        }
    ]
]
```

https://github.com/axa-group/Parsr/blob/master/docs/configuration.md#5-exempli-gratia
