### ISSUE TITLE
Error on docker-compose build under Windows

### ISSUE THREAD

**Issue by aarohijohal** [axa-group/Parsr#56]
**Summary**
An error shows up when `docker-compose build` is launched in the root directory, causing the installation to fail.

**Steps To Reproduce**
1. Clone the repository.
2. In the root folder, type `docker-compose build`

**Expected behavior**
A working installation of Parsr.

**Actual behavior**
https://gist.github.com/aarohijohal/804196e1f308fd6054eac22201e7892f

**Environment**
 - OS: Windows
 - Other details can be extracted if need be

**Comment by slallemand** [comment]
Duckling is no more needed in latest version of parsr.
Also, it's no more needed to build the docker images as they are published on the docker hub (latest version of the docker-compose file reflect that)
