### ISSUE TITLE
Unable to Run API using Python

### ISSUE THREAD

**Issue by ShivamSharma2705** [axa-group/Parsr#603]
Hi, I am trying to run the demo and am getting the following:

Error: File not found at FileManager.checkFile (C:\Users\shar703\Desktop\Parsr-master\api\server\dist\FileManager.js:104:19) at FileManager.getFilePath (C:\Users\shar703\Desktop\Parsr-master\api\server\dist\FileManager.js:71:25) at ApiServer. (C:\Users\shar703\Desktop\Parsr-master\api\server\dist\api.js:446:49) at step (C:\Users\shar703\Desktop\Parsr-master\api\server\dist\api.js:67:23) at Object.next (C:\Users\shar703\Desktop\Parsr-master\api\server\dist\api.js:48:53) at C:\Users\shar703\Desktop\Parsr-master\api\server\dist\api.js:42:71 at new Promise () at __awaiter (C:\Users\shar703\Desktop\Parsr-master\api\server\dist\api.js:38:12) at ApiServer.handleGetFile (C:\Users\shar703\Desktop\Parsr-master\api\server\dist\api.js:437:16) at ApiServer.handleGetMarkdown (C:\Users\shar703\Desktop\Parsr-master\api\server\dist\api.js:431:14)

When I render any output. 
The attached is the output from my parsr API
<img width="946" alt="Parsr error" src="https://user-images.githubusercontent.com/94197666/165175689-975515ac-1949-4b96-bfee-3c1a2af3ab44.PNG">

The api says 

"Python not found"

**Comment by BinaryBrain** [comment]
You need to install Python and it should be able to run when you type `python` in your terminal.

**Comment by ShivamSharma2705** [comment]
Yeah, python is installed
