### ISSUE TITLE
python3 command is just python sometimes

### ISSUE THREAD

**Issue by BinaryBrain** [axa-group/Parsr#63]
**Summary**
On Archlinux and some other OS (maybe Windows as well?), python 3.x is ran using the `python` command and python 2.x using the `python2` command. Here, we're assuming it's always `python3`: https://github.com/axa-group/Parsr/blob/dc3bec7ae62b0db12a075f31c26ba8951a63c2f7/server/src/modules/TableDetectionModule/TableDetectionModule.ts#L35

**Steps To Reproduce**
1. Have your path with `python` pointing on Python 3.x
2. Remove `python3` from your path.

**Expected behavior**
Table extraction should run.

**Actual behavior**
A node error: `Error: spawnSync python3 ENOENT`.

**Environment**
 - Reference commit/version: `dc3bec7ae62b0db12a075f31c26ba8951a63c2f7`
 - Other platform details: Python 3.x is just `python`, not `python3`
 - OS: Arch Linux, maybe others?

**Comment by BinaryBrain** [comment]
I'm unsure but we may have the same issue on the Docker container.

**Comment by aarohijohal** [comment]
Commit 387707b should resolve this but the docker container still needs a look.
