### ISSUE TITLE
In raw text extraction outputs, handle bulleted and numbered lists

### ISSUE THREAD

**Issue by aarohijohal** [axa-group/Parsr#9]
Currently, the output of the pdf2json and tesseract extractors do not give us any information about the numbered or bulleted lists.
The current bullet/numbered list detection module `ListDetectionModule` needs to be improved.

**Current state**
Source
![image](https://user-images.githubusercontent.com/1119728/63242404-9d38ac80-c29a-11e9-8d77-19324886ca35.png)
Resulting Markdown
![image](https://user-images.githubusercontent.com/1119728/63242419-a4f85100-c29a-11e9-9814-0f442fd9f3af.png)

**Comment by BinaryBrain** [comment]
This is fixed by the recent improvements of List Detections.
