### ISSUE TITLE
Fails on openshift Kubernetes `EACCES: permission denied, mkdir '/opt/app-root/src/api/server/dist/output'`

### ISSUE THREAD

**Issue by peter-vandenabeele-axa** [axa-group/Parsr#90]
**Summary**
Trying to run the container on Openshift 3 Kubernetes fails. By default openshift runs in non-root mode. The program tries to create a directory (`dist/output`) and this fails.

The code that writes this output directory is here:
https://github.com/axa-group/Parsr/blob/develop/api/server/src/api.ts#L55-L59

**Steps To Reproduce**

```
$ oc run parsr --image=axarev/parsr --expose=true --port=3001
...
$ oc logs parsr-1-6wchv
Starting par.sr API : node api/server/dist/index.js
fs.js:115
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/opt/app-root/src/api/server/dist/output'
    at Object.mkdirSync (fs.js:753:3)
    at new ApiServer (/opt/app-root/src/api/server/dist/api.js:63:16)
    at Object.<anonymous> (/opt/app-root/src/api/server/dist/index.js:19:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Expected behavior**
The pod should be running. It does run properly in a default GKE cluster.

**Actual behavior**
The container fails to run, because it cannot create the directory.
It goes in a restart loop.

**Environment**
 - Docker hub version https://hub.docker.com/layers/axarev/parsr/latest/images/sha256-b4adf5d95317f4a9c3ce79bd708bd6bdf6abde7b4bc553880af711b3b69e410f
 - Other platform details: Openshift version 3.9

**Additional context**
The fact that openshift by default only allows non-root is documented e.g. here:
https://stackoverflow.com/questions/42363105/permission-denied-mkdir-in-container-on-openshift

I think it would be better if we can change the set-up of the container that it can run as non-root.

**Comment by slallemand** [comment]
Hello @peter-vandenabeele-axa 
The container itself is not working as root to be compliant with Openshift.
BTW, it seems the directory can't be created by that user. I will test it on my side.

Also, maybe you can attach and mount a PVC on /opt/app-root/src/api/server/dist/output.
Let me know

**Comment by peter-vandenabeele-axa** [comment]
Thanks for the fast feedback. I will investigate tomorrow.

**Comment by slallemand** [comment]
Did a quick test on Openshift with a PVC and that should fix the issue.
By the way, I will update the docker image so that the permissions are ok (as you know openshift use a random user to start the container with group root)

**Comment by peter-vandenabeele-axa** [comment]
Thanks :-)

Indeed, adding a pvc mount on that location, acts as a work-around. This is the pod template for the deploymentConfig that now works:

```
Pod Template:
  Labels:       run=parsr
  Containers:
   parsr:
    Image:              axarev/parsr
    Port:               3001/TCP
    Environment:        <none>
    Mounts:
      /opt/app-root/src/api/server/dist/output from volume-7tb99 (rw)
  Volumes:
   volume-7tb99:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pvc-test-parsr
    ReadOnly:   false
```

**Comment by peter-vandenabeele-axa** [comment]
I tested the fix in https://github.com/axa-group/Parsr/commit/aa5896a86cf4fcd79e07e03def0e5e1f95634cb7 and I can confirm it now starts without an explicit pvc.

I will close this isssue as it is now resolved.

Thanks for the fast resolution :-)
